sudo: required
services:
  - docker

before_install:
  - docker build -t vineeshva/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run vineeshva/react-test npm test -- --coverage

after_success:
  - docker build -t vineeshva/multi-client ./client
  - docker build -t vineeshva/multi-nginx ./nginx
  - docker build -t vineeshva/multi-server ./server
  - docker build -t vineeshva/multi-worker ./worker
  # Log into to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  #Take those images and push that into docker hub
  - docker push vineeshva/multi-client
  - docker push vineeshva/multi-nginx
  - docker push vineeshva/multi-server
  - docker push vineeshva/multi-worker



